In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from word2number import w2n

In [2]:
import sys
!{sys.executable} -m pip install word2number

  Created wheel for word2number: filename=word2number-1.1-cp37-none-any.whl size=5591 sha256=c0c44a514d295b8c6e12786caab9ca72f1b3eea5fa1b3b93e592e65d3011250a
  Stored in directory: C:\Users\USER-01\AppData\Local\pip\Cache\wheels\46\2f\53\5f5c1d275492f2fce1cdab9a9bb12d49286dead829a4078e0e
Successfully built word2number


In [2]:
df = pd.read_csv('hiring.csv')

In [3]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

### To handle the missing values we will try to fill those datapoints with the median of the column


In [4]:
df.experience

0       NaN
1       NaN
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [5]:
df.experience=df.experience.fillna('zero')

In [6]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [7]:
df['experience']=df['experience'].apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [8]:
import math
median_test_score=math.floor(df['test_score(out of 10)'].median())
median_test_score

8

In [12]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [13]:
regression=linear_model.LinearRegression()

In [14]:
regression.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
regression.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [16]:
regression.intercept_

17737.26346433771

In [17]:
regression.predict([[10,8.0,7]])

array([76069.1411936])

In [19]:
regression.predict([[2,9,6]])

array([53205.96797671])

In [20]:
import pickle


In [21]:
with open('modelpickle_linearReg','wb') as file:
    pickle.dump(regression,file)

In [22]:
with open('modelpickle_linearReg','rb') as file:
    mp=pickle.load(file)

In [24]:
mp.predict([[2,9,6]])

array([53205.96797671])